#!/usr/bin/env python3

import time

csi = "\x1B["
reset = f"{csi}0m"
greenback = f"{csi}43m"
greyback = f"{csi}48;2;192;192;192m"

def print_raw(*args, **kwargs):
	print(*args, **kwargs, end = '', flush = True)

print(f'foo{csi}Cbar')
print(f'foo xar{csi}D{csi}D{csi}Db')
print(f'{greenback}foo {greyback}bar{reset}')

# Tests of Line::replace_characters().
# Splitting a run.
print(f'foo xar\b\b\b{greenback}b{reset}')
# Grow a run.
print(f'foo x\bbar')
# Before a run.
print(f"foo {greyback}bar\b\b\b{reset}{greenback}b{reset}")
# Within a run.
print(f"xxx xar\b\b\b\b\b\b\bfoo b")
# Unsplitting a run.
print(f"{greenback}xxx x{reset}ar\b\b\b\b\b\b\bfoo b")
# Replacing multiple runs.
print(f"{csi}31mx{csi}32mx{csi}33mx {csi}34mx{reset}ar\rfoo b")
# !!! NEED MORE! AND DELETION! !!!


# Cursor disable/enable.
def cursor_disable_test():
	print(f"foo bar\b\b\b{csi}?25l", end = '', flush = True)
	time.sleep(1)
	print(f"{csi}?25h", end = '', flush = True)
	time.sleep(1)
	print()
# cursor_disable_test()

# Inverse.
def inverse_test():
	print_raw(f"{csi}7mfoo{csi}27m bar\r")
	for i in range(7):
		time.sleep(1)
		print_raw(f"{csi}C")
	time.sleep(1)
	print()
# inverse_test()



