#!/usr/bin/env python3

alphabet = "abcdefghijklmnopqrstuvwxyz"

print("\x1B[?5001h", end = '')
for i in range(10010):
	print(f"{i}\t{alphabet[:(i % len(alphabet)) + 1]}")
print("\x1B[?5001l", end = '')

