#!/usr/bin/env python3

import sys

n = 10010
if len(sys.argv) > 1:
	n = int(sys.argv[1])

alphabet = "abcdefghijklmnopqrstuvwxyz"

print("\x1B[?5001h", end = '')
for i in range(n):
	print(f"{i}\t{alphabet[:(i % len(alphabet)) + 1]}")
print("\x1B[?5001l", end = '')

