#!/usr/bin/env python3

import sys

output = [
	b"\x1B(0",
	b"\x6C\x71\x77\x71\x6B\n",
	b"\x78 \x78 \x78\n",
	b"\x74\x71\x6E\x71\x75\n",
	b"\x78 \x78 \x78\n",
	b"\x6D\x71\x76\x71\x6A\n"
	b"\x1B(B\n",
	]

sys.stdout.buffer.write(b"".join(output))

