#!/usr/bin/env python3

import time, sys

intra_test_time = 1
inter_test_time = 2

alt_screen = False

csi = "\x1B["
reset = f"{csi}0m"
clear_to_eos = f"{csi}J"
clear_screen = f"{csi}2J"

def print_raw(*args, **kwargs):
	print(*args, **kwargs, end = '', flush = True)

def up(n):
	return f"{csi}{n}A"

def test_start(banner):
	print(f"=== {banner} ===")
	print()

def test_end(num_lines):
	time.sleep(inter_test_time)
	print_raw(f"{up(num_lines + 2)}{clear_to_eos}")

def prefer_alt(test_name):
	if not alt_screen:
		print(f'It might be better to use "alt" for the {test_name} test.')
		time.sleep(intra_test_time)
		print_raw(f"{csi}H{csi}2J")

def ten_lines():
	print("=====")
	for i in range(10):
		print(i + 1)
	print("=====")


def clear_to_eos_test():
	test_start("Clear to end of screen")
	print(f"This text...")
	print(f"...will be deleted")
	time.sleep(intra_test_time)
	print(f"{up(2)}{csi}J", end = '', flush = True)
	test_end(0)


def delete_lines_test():
	test_start("Delete lines")
	print(f"======")
	for i in range(5):
		print(i + 1)
	print(f"======")
	time.sleep(intra_test_time)
	print_raw(f"{up(6)}{csi}2M")
	# Only test the margin version in full-screen, since we can't (yet)
	# interrogate the cursor position.
	if (alt_screen):
		time.sleep(intra_test_time)
		print_raw(f"{csi}4;6r{csi}M{csi}r")
	test_end(1)


def margined_newline_test():
	prefer_alt('margined-newline')
	test_start("Margined newline")
	ten_lines()
	print_raw(f"{csi}13;1H{csi}4;13r")
	time.sleep(intra_test_time)
	for i in range(4):
		print_raw(f"\n- {i}")
		time.sleep(intra_test_time)
	for i in range(10):
		print()
	print_raw(f"{csi}4;1H")
	for i in range(12):
		print(i)
		time.sleep(intra_test_time)
	print_raw(f"{csi}r")
	test_end(12)


def full_screen_scroll_test():
	test_start("Full screen scroll")
	time.sleep(intra_test_time)
	print_raw(f"{csi}T")
	time.sleep(intra_test_time)
	print_raw(f"{csi}S")
	time.sleep(intra_test_time)
	test_end(0)


def margined_scroll_test():
	prefer_alt("margined-scroll")
	test_start("Margined scroll")
	ten_lines()
	time.sleep(intra_test_time)
	print_raw(f"{csi}4;13r{csi}T")
	time.sleep(intra_test_time)
	print_raw(f"{csi}S")
	time.sleep(intra_test_time)
	print_raw(f"{csi}r")
	test_end(12)


def null_test():
	test_start("Null")
	test_end(0)

tests = {
	'clear-to-eos': clear_to_eos_test,
	'delete-lines': delete_lines_test,
	'margined-newline': margined_newline_test,
	'full-screen-scroll': full_screen_scroll_test,
	'margined-scroll': margined_scroll_test,
	'null': null_test,
	}



did_a_test = False
for arg in sys.argv[1:]:
	if arg == "alt":
		if not alt_screen:
			print(f"{csi}?1049h{clear_screen}", end = '', flush = True)
			alt_screen = True
	elif arg == "!alt":
		if alt_screen:
			print(f"{csi}?1049l", end = '', flush = True)
			alt_screen = False
	else:
		tests[arg]()
		did_a_test = True

if alt_screen:
	print(f"{csi}?1049l", end = '', flush = True)

if not did_a_test:
	print(f"Usage: {sys.argv[0]} [<test> | alt | !alt]...")
	print(f'"alt" enters alternate-screen mode, "!alt" exits it.')
	print(f"Available tests: {', '.join(tests.keys())}")


