#!/usr/bin/env python3

csi = "\x1B["
reset = f"{csi}0m"
greenback = f"{csi}43m"
blueback = f"{csi}44m"
greyback = f"{csi}48;2;192;192;192m"

print(f"{blueback} {greyback} " * 3 + f"{reset} foo bar baz")
print("  " * 3 + " foo bar baz")
